- name: "ansiblemanager"
  hosts: all
  tasks:
  - name: "ansiblemanager | install git"
    ansible.builtin.package:
      name: git
      state: latest
    become: yes

  - name: "ansiblemanager | install python3-virtualenv"
    ansible.builtin.apt:
      name: python3-virtualenv
      state: latest
    become: yes

  - name: "ansiblemanager |Add the automation group"
    ansible.builtin.group:
      name: "{{ serviceaccount['name'] }}"
      state: present
    become: yes

  - name: "ansiblemanager |Add the automation user"
    ansible.builtin.user:
      name: "{{ serviceaccount['name'] }}"
      comment: "{{ serviceaccount['gecos'] }}"
      group: "{{ serviceaccount['name'] }}"
    become: yes

  - name: Create a 2048-bit SSH key for  automation user
    ansible.builtin.user:
      name: "{{ serviceaccount['name'] }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    become_user: "{{ serviceaccount['name'] }}"
    become: yes

  - name: "Ansiblemanager | clone the main ansible manager feeder "
    ansible.builtin.git:
      repo: "https://github.com/miracle-as/openknowit_kalm.git"
      dest: /opt/openknowit_kalm
      single_branch: yes
      force: yes
      version: main
    become: yes

  - name: "Ansiblemanager | pip install kalm"
    ansible.builtin.pip:
      name: https://github.com/miracle-as/openknowit_kalm.git 



