- name: "ansiblemanager"
  hosts: all
  tasks:
  - name: "ansiblemanager | install git"
    ansible.builtin.package:
      name: git
      state: latest

  - name: "ansiblemanager |Add the automation group"
    ansible.builtin.group:
      name: "{{ aaoaa_serviceaccount['name'] }}"
      state: present
    become: yes


  - name: "ansiblemanager |Add the automation user"
    ansible.builtin.user:
      name: "{{ aaoaa_serviceaccount['name'] }}"
      comment: "{{ aaoaa_serviceaccount['gecos'] }}"
      group: "{{ aaoaa_serviceaccount['name'] }}"
    become: yes

  - name: Create a 2048-bit SSH key for  automation user
    ansible.builtin.user:
      name: "{{ aaoaa_serviceaccount['name'] }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    become_user: "{{ aaoaa_serviceaccount['name'] }}"
    become: yes

  - name: "Ansiblemanager | clone the main ansible manager feeder "
    ansible.builtin.git:
      repo: "git@github.com:JakobHolstDK/openknowit_ansible_feed.git"
      dest: /opt/openknowit_ansible_feed
      single_branch: yes
      force: yes
      version: main
    become: yes
  
  - name: "Ansiblemanager | clone the main ansible manager network"
    ansible.builtin.git:
      repo: "git@github.com:JakobHolstDK/openknowit_ansibleautomation_main.git"
      dest: /opt/openknowit_ansibleautomation_main
      single_branch: yes
      force: yes
      version: main
    become: yes
    
  - name: "ansiblemanager | copy service file to manager"
    ansible.builtin.template:
      src: aaoaa.service.j2
      dest: /usr/lib/systemd/system/aaoaa.service
      mode: '0644'      
    notify: 
      - "restart ansiblemanager service"
    become: yes

  - name: "ansiblemanager | Ensure ansible manager serivice is runnig"
    service: 
      name: "aaoaa"
      state: started
      enabled: true
    become: yes

  - name: "ansiblemanager | Run custom setup"
    command:  
    become_user: "{{ aaoaa_serviceaccount['name'] }}"
    become: yes

  handlers:
    - name: "restart ansiblemanager service"
      service: 
        name: "aaoaa"
        state: restarted
      become: yes

