- name: "ansiblemanager"
  hosts: all
  tasks:
  - name: "ansiblemanager| install git"
    ansible.builtin.package:
      name: git
      state: latest

  - name: "Example clone of a single branch"
    ansible.builtin.git:
      repo: "git@github.com:JakobHolstDK/openknowit_ansibleautomation_main.git"
      dest: /opt/openknowit_ansibleautomation_main
      single_branch: yes
      force: yes
      version: main
    become: yes
    
  - name: "ansiblemanager | ensure systemd user directory exitst"
    ansible.builtin.file:
      path: ~/.config/systemd/user
      state: directory
      mode: '0755'
  
  - name: "ansiblemanager | copy service file to manager"
    ansible.builtin.copy:
      src: aaoaa.service
      dest: ~/.config/systemd/user/aaoaa.service
      mode: '0644'      
 

