- name: "ansiblemanager"
  hosts: all
  tasks:
  - name: "ansiblemanager | install git"
    ansible.builtin.package:
      name: git
      state: latest
    become: yes

  - name: "ansiblemanager |Add the automation group"
    ansible.builtin.group:
      name: "{{ serviceaccount['name'] }}"
      state: present
    become: yes

  - name: "ansiblemanager |Add the automation user"
    ansible.builtin.user:
      name: "{{ serviceaccount['name'] }}"
      comment: "{{ serviceaccount['gecos'] }}"
      group: "{{ serviceaccount['name'] }}"
    become: yes

  - name: "Ansiblemanager | pip install awxcli"
    ansible.builtin.pip:
      name: https://releases.ansible.com/ansible-tower/cli/ansible-tower-cli-latest.tar.gz
    become: yes
    become_user: "{{ serviceaccount['name'] }}"

  - name: "Ansiblemanager | pip install kalm"
    ansible.builtin.pip:
      name: kalm
    become: yes
    become_user: "{{ serviceaccount['name'] }}"

  - name: "Ansiblemanager | Create the service file"
    ansible.builtin.template:
      src: kalm.service.j2
      dest: /etc/systemd/system/kalm.service
      owner: root
      group: root
      mode: '0644'
    become: yes

  - name: "Ansiblemanager | Chreate the service file checker"
    ansible.builtin.copy:
       src:  managekalmservicefile.sh
       dest: /usr/local/bin/managekalmservicefile.sh
       mode: 0755
     become: yes








